# Imports

In [3]:
import pandas as pd

df = pd.read_csv('../../datasets/stars.csv')
print(df.shape)
df.head(10)

(240, 7)

,Temperature (K),Luminosity(L/Lo),Radius(R/Ro),Absolute magnitude(Mv),Star type,Star color,Spectral Class
0,3068,0.002400,0.1700,16.12,0,Red,M
1,3042,0.000500,0.1542,16.60,0,Red,M
2,2600,0.000300,0.1020,18.70,0,Red,M
3,2800,0.000200,0.1600,16.65,0,Red,M
4,1939,0.000138,0.1030,20.06,0,Red,M
5,2840,0.000650,0.1100,16.98,0,Red,M
6,2637,0.000730,0.1270,17.22,0,Red,M
7,2600,0.000400,0.0960,17.40,0,Red,M
8,2650,0.000690,0.1100,17.45,0,Red,M
9,2700,0.000180,0.1300,16.05,0,Red,M

# Preprocessing

In [4]:
# Preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split

# Create LabelEncoder instances
color_encoder = LabelEncoder()
spectral_encoder = LabelEncoder()

# Encode categorical variables
df['Star color'] = color_encoder.fit_transform(df['Star color'])
df['Spectral Class'] = spectral_encoder.fit_transform(df['Spectral Class'])

# Print unique values and their encodings
print("\nStar Color Encodings:")
for color, code in zip(color_encoder.classes_, range(len(color_encoder.classes_))):
    print(f"{color}: {code}")

print("\nSpectral Class Encodings:")
for spec, code in zip(spectral_encoder.classes_, range(len(spectral_encoder.classes_))):
    print(f"{spec}: {code}")

# Prepare features and target
X = df.drop("Star type", axis=1)
y = df["Star type"]

# Split into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print("\nTraining set shape:", X_train.shape)
print("Test set shape:", X_test.shape)

Star Color Encodings:
Blue: 0
Blue : 1
Blue White: 2
Blue white: 3
Blue white : 4
Blue-White: 5
Blue-white: 6
Orange: 7
Orange-Red: 8
Pale yellow orange: 9
Red: 10
White: 11
White-Yellow: 12
Whitish: 13
Yellowish: 14
Yellowish White: 15
white: 16
yellow-white: 17
yellowish: 18

Spectral Class Encodings:
A: 0
B: 1
F: 2
G: 3
K: 4
M: 5
O: 6

Training set shape: (168, 6)
Test set shape: (72, 6)

# Train a machine learning model

In [5]:

# Train a machine learning model
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf.fit(X_train, y_train)

# Make prediction on the testing data
y_pred = clf.predict(X_test)

# Classification Report
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        12
           2       1.00      1.00      1.00        10
           3       1.00      1.00      1.00        10
           4       1.00      1.00      1.00        11
           5       1.00      1.00      1.00        15

    accuracy                           1.00        72
   macro avg       1.00      1.00      1.00        72
weighted avg       1.00      1.00      1.00        72